// Auto-generated by scripts/parse-lesson-tsvs.ts — do not edit manually
import type { LessonContent } from "../types";

import lesson01 from "./lesson-01.json";
import lesson02 from "./lesson-02.json";
import lesson03 from "./lesson-03.json";
import lesson04 from "./lesson-04.json";
import lesson05 from "./lesson-05.json";
import lesson06 from "./lesson-06.json";
import lesson07 from "./lesson-07.json";
import lesson08 from "./lesson-08.json";
import lesson09 from "./lesson-09.json";
import lesson10 from "./lesson-10.json";
import lesson11 from "./lesson-11.json";
import lesson12 from "./lesson-12.json";
import lesson13 from "./lesson-13.json";
import lesson14 from "./lesson-14.json";
import lesson15 from "./lesson-15.json";
import lesson16 from "./lesson-16.json";
import lesson17 from "./lesson-17.json";
import lesson18 from "./lesson-18.json";
import lesson19 from "./lesson-19.json";
import lesson20 from "./lesson-20.json";
import lesson21 from "./lesson-21.json";
import lesson22 from "./lesson-22.json";
import lesson23 from "./lesson-23.json";
import lesson24 from "./lesson-24.json";
import lesson25 from "./lesson-25.json";
import lesson26 from "./lesson-26.json";
import lesson27 from "./lesson-27.json";
import lesson28 from "./lesson-28.json";
import lesson29 from "./lesson-29.json";
import lesson30 from "./lesson-30.json";
import lesson31 from "./lesson-31.json";
import lesson32 from "./lesson-32.json";

export const LESSONS: LessonContent[] = [
  lesson01,
  lesson02,
  lesson03,
  lesson04,
  lesson05,
  lesson06,
  lesson07,
  lesson08,
  lesson09,
  lesson10,
  lesson11,
  lesson12,
  lesson13,
  lesson14,
  lesson15,
  lesson16,
  lesson17,
  lesson18,
  lesson19,
  lesson20,
  lesson21,
  lesson22,
  lesson23,
  lesson24,
  lesson25,
  lesson26,
  lesson27,
  lesson28,
  lesson29,
  lesson30,
  lesson31,
  lesson32,
];
