/**
 * Build script: parses lesson.json + vocabulary.tsv + exercises.tsv
 * from docs/pali-lessons/pali-primer-extracted-lesson-content/
 * and outputs bundled JSON files to data/lessons/content/
 *
 * Run: npx tsx scripts/parse-lesson-tsvs.ts
 */

import * as fs from "fs";
import * as path from "path";

const LESSONS_SOURCE = path.resolve(
  __dirname,
  "../docs/pali-lessons/pali-primer-extracted-lesson-content",
);
const OUTPUT_DIR = path.resolve(__dirname, "../data/lessons/content");
const TOTAL_LESSONS = 32;

type VocabItem = { pali: string; english: string; type: string; gender: string };
type ExerciseItem = { pali: string; english: string };

function parseTsv<T>(filePath: string, mapper: (cols: string[]) => T): T[] {
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, "utf-8").trim();
  const lines = content.split("\n");
  // Skip header row
  return lines
    .slice(1)
    .filter((line) => line.trim().length > 0)
    .map((line) => mapper(line.split("\t")));
}

function parseVocabulary(filePath: string): VocabItem[] {
  return parseTsv(filePath, (cols) => ({
    pali: cols[0]?.trim() ?? "",
    english: cols[1]?.trim() ?? "",
    type: cols[2]?.trim() ?? "",
    gender: cols[3]?.trim() ?? "",
  }));
}

function parseExercises(filePath: string): ExerciseItem[] {
  return parseTsv(filePath, (cols) => ({
    pali: cols[0]?.trim() ?? "",
    english: cols[1]?.trim() ?? "",
  }));
}

// Ensure output directory exists
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const lessonImports: string[] = [];

for (let i = 1; i <= TOTAL_LESSONS; i++) {
  const num = String(i).padStart(2, "0");
  const lessonDir = path.join(LESSONS_SOURCE, `lesson-${num}`);

  // Read lesson.json
  const lessonJsonPath = path.join(lessonDir, "lesson.json");
  if (!fs.existsSync(lessonJsonPath)) {
    console.error(`Missing lesson.json for lesson ${num}, skipping`);
    continue;
  }
  const lessonData = JSON.parse(fs.readFileSync(lessonJsonPath, "utf-8"));

  // Parse TSVs
  const vocabulary = parseVocabulary(path.join(lessonDir, "vocabulary.tsv"));
  const exercises = parseExercises(path.join(lessonDir, "exercises.tsv"));

  // Combine
  const combined = {
    lesson_number: lessonData.lesson_number,
    title: lessonData.title,
    topic: lessonData.topic,
    grammar: lessonData.grammar,
    vocabulary,
    exercises,
  };

  // Write JSON
  const outPath = path.join(OUTPUT_DIR, `lesson-${num}.json`);
  fs.writeFileSync(outPath, JSON.stringify(combined, null, 2) + "\n");
  console.log(`Generated lesson-${num}.json (${vocabulary.length} vocab, ${exercises.length} exercises)`);

  lessonImports.push(
    `import lesson${num} from "./lesson-${num}.json";`,
  );
}

// Generate index.ts
const indexContent = `// Auto-generated by scripts/parse-lesson-tsvs.ts — do not edit manually
import type { LessonContent } from "../types";

${lessonImports.join("\n")}

export const LESSONS: LessonContent[] = [
${Array.from({ length: TOTAL_LESSONS }, (_, i) => `  lesson${String(i + 1).padStart(2, "0")},`).join("\n")}
];
`;

fs.writeFileSync(path.join(OUTPUT_DIR, "index.ts"), indexContent);
console.log(`\nGenerated index.ts with ${TOTAL_LESSONS} lesson imports`);
